name: Ultroid

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "HNDLDR"

          replace: "HNDLR"

      - name: Create PR

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Fuck Typos'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: ProgrammingError

          commit_user_email: error@notavailable.live
